### PR TITLE
Token requestor remove PAR

### PR DESCRIPTION
**Pull request by torgeirfr**
- Removes PAR from token requestor callback

### CODE REVIEW

**Comment by adrianhj88** [comment]
LGTM. Should we wait with merge until rest is finished?

**Review by thxmasj — APPROVED** [review]

**Comment by thxmasj** [comment]
> LGTM. Should we wait with merge until rest is finished?

Any reason for waiting?

**Comment by adrianhj88** [comment]
> > LGTM. Should we wait with merge until rest is finished?
> 
> Any reason for waiting?

If we need to add something else on top of master in this repo, then we would also remove PAR for this development. And if it is not removed in the other repo we would have compiling errors. Already been there twice where PR in the other repo had to include "fake" code to avoid compiling errors while waiting for merge of another branch.

If this is not the case here, then go ahead!

**Comment by thxmasj** [comment]
> > > LGTM. Should we wait with merge until rest is finished?
> > 
> > 
> > Any reason for waiting?
> 
> If we need to add something else on top of master in this repo, then we would also remove PAR for this development. And if it is not removed in the other repo we would have compiling errors. Already been there twice where PR in the other repo had to include "fake" code to avoid compiling errors while waiting for merge of another branch.
> 
> If this is not the case here, then go ahead!

You are right. I was thinking that it would be such a simple thing to just remove the setting of the PAR on the DTO, but it is still cleaner to wait.

**Pull request merged**
